# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'M4C' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for M4C
  pod 'MBProgressHUD', '~> 1.1'
  pod 'IQKeyboardManager', '~> 5.0'
  pod 'SwiftyJSON'
  pod 'AFNetworking'
  pod 'SWRevealViewController'
  pod 'SDWebImage'
  pod 'SwiftyUserDefaults' , :git => 'https://github.com/radex/SwiftyUserDefaults'
end
